In [25]:
import pandas as pd

In [27]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
combine = [train_df, test_df]

In [95]:
import numpy as np
train_df.describe(exclude=[np.object])

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [128]:
train_df[['Age', 'Survived','Pclass']].groupby(['Age']).mean()

       Survived    Pclass
Age
0.42   1.000000  3.000000
0.67   1.000000  2.000000
0.75   1.000000  3.000000
0.83   1.000000  2.000000
0.92   1.000000  1.000000
1.00   0.714286  2.714286
2.00   0.300000  2.600000
3.00   0.833333  2.500000
4.00   0.700000  2.600000
5.00   1.000000  2.750000
6.00   0.666667  2.666667
7.00   0.333333  2.666667
8.00   0.500000  2.500000
9.00   0.250000  3.000000
10.00  0.000000  3.000000
11.00  0.250000  2.500000
12.00  1.000000  3.000000
13.00  1.000000  2.500000
14.00  0.500000  2.500000
14.50  0.000000  3.000000
15.00  0.800000  2.600000
16.00  0.352941  2.529412
17.00  0.461538  2.384615
18.00  0.346154  2.461538
19.00  0.360000  2.360000
20.00  0.200000  3.000000
20.50  0.000000  3.000000
21.00  0.208333  2.583333
22.00  0.407407  2.555556
23.00  0.333333  2.133333
...         ...       ...
44.00  0.333333  2.111111
45.00  0.416667  2.000000
45.50  0.000000  2.000000
46.00  0.000000  1.333333
47.00  0.111111  1.777778
48.00  0.666667  1.666667
49.00  0.666667  1.333333
50.00  0.500000  1.600000
51.00  0.285714  2.000000
52.00  0.500000  1.333333
53.00  1.000000  1.000000
54.00  0.375000  1.500000
55.00  0.500000  1.500000
55.50  0.000000  3.000000
56.00  0.500000  1.000000
57.00  0.000000  2.000000
58.00  0.600000  1.000000
59.00  0.000000  2.500000
60.00  0.500000  1.250000
61.00  0.000000  1.666667
62.00  0.500000  1.250000
63.00  1.000000  2.000000
64.00  0.000000  1.000000
65.00  0.000000  1.666667
66.00  0.000000  2.000000
70.00  0.000000  1.500000
70.50  0.000000  3.000000
71.00  0.000000  1.000000
74.00  0.000000  3.000000
80.00  1.000000  1.000000

[88 rows x 2 columns]